FROM registry.redhat.io/ubi9/go-toolset:1.26@sha256:17c888d75753f128f6cbdc5587932c3abd2632ca8e0931aa27b9a60c7a75ac62 as builder

WORKDIR /go/src/github.com/trustyai-explainability/trustyai-service-operator
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download
# Copy the go source
COPY cmd/ cmd/
COPY api/ api/
COPY controllers/ controllers/

# Copy license
COPY LICENSE /licenses/ta-lmes-driver.md

USER root
RUN GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOEXPERIMENT=strictfipsruntime \
    go build -tags 'strictfipsruntime netgo' -o /bin/driver ./cmd/lmes_driver/*.go

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:44bc70ef6e6ea9a70e353be97f4722e10358d09fbb9494ca943b2a641049690e

COPY --from=builder /bin/driver /bin/driver

USER 65532:65532

WORKDIR /bin

ENTRYPOINT [ "/bin/driver" ]

LABEL name="rhoai/odh-ta-lmes-driver-rhel9" \
      com.redhat.component="odh-ta-lmes-driver-rhel9" \
      io.k8s.display-name="odh-ta-lmes-driver-rhel9" \
      io.k8s.description="Kubernetes-native execution engine that coordinates language model evaluation jobs using frameworks such as lm-evaluation-harness and Unitxt, supporting evaluation tasks with automatic device detection and progress monitoring." \
      description="Kubernetes-native execution engine that coordinates language model evaluation jobs using frameworks such as lm-evaluation-harness and Unitxt, supporting evaluation tasks with automatic device detection and progress monitoring." \
      summary="Kubernetes-native execution engine that coordinates language model evaluation jobs" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
