FROM registry.redhat.io/ubi9/go-toolset:1.26@sha256:0a4666f7a4eb0644c97a73cba198eb268691b270d97831822689e7a2088f87be AS builder

WORKDIR /go/src/github.com/trustyai-explainability/trustyai-service-operator
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download
# Copy the go source
COPY cmd/ cmd/
COPY api/ api/
COPY controllers/ controllers/

# Copy license
COPY LICENSE /licenses/ta-lmes-driver.md

USER root
RUN GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOEXPERIMENT=strictfipsruntime \
    go build -tags 'strictfipsruntime netgo' -o /bin/driver ./cmd/lmes_driver/*.go

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:1d7c5517a4a1a8e2688620b39ee980e82505ca1ab7ae5541b5463120ae9b3897

COPY --from=builder /bin/driver /bin/driver

USER 65532:65532

WORKDIR /bin

ENTRYPOINT [ "/bin/driver" ]

LABEL name="rhoai/odh-ta-lmes-driver-rhel9" \
      com.redhat.component="odh-ta-lmes-driver-rhel9" \
      io.k8s.display-name="odh-ta-lmes-driver-rhel9" \
      io.k8s.description="Kubernetes-native execution engine that coordinates language model evaluation jobs using frameworks such as lm-evaluation-harness and Unitxt, supporting evaluation tasks with automatic device detection and progress monitoring." \
      description="Kubernetes-native execution engine that coordinates language model evaluation jobs using frameworks such as lm-evaluation-harness and Unitxt, supporting evaluation tasks with automatic device detection and progress monitoring." \
      summary="Kubernetes-native execution engine that coordinates language model evaluation jobs" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
